### ISSUE TITLE
OSM Objects

### ISSUE THREAD

**Issue by sfkeller** [sosm/osmhistorydb-ch#1]
tbd.

**Comment by samadelli** [comment]
Datenbank: Läuft in Testumgebung
cronjob: tbd.
osm_pg_db_clipper: tbd.

**Comment by sfkeller** [comment]
@samadelli Die Query von osm_pg_db_clipper `delete from ways w where not exists (select from nodes n where n.id = any(w.nodes));` scheint ja langsam zu sein: https://explain.depesz.com/s/6MpU

Wenn die `id` Werte niemals `NULL` sind, könnte die einfachere `NOT EXISTS`-Form verwendet werden:

```SQL
DELETE FROM ways w
WHERE NOT EXISTS (
  SELECT 1 FROM nodes
   WHERE id = ANY (w.nodes)
)
```
Kannst du das mal ggf. anpassen und probieren?

**Comment by datendelphin** [comment]
Das entspricht auch ungefär meiner Erfahrung. Gewisse varianten verwenden den Index nicht und sind langsam. Hatte auch schon Erfolg mit der not exists variante.

**Comment by sfkeller** [comment]
Dieser Issue scheint gelöst zu sein.
