### ISSUE TITLE
Possibility to set a data range

### ISSUE THREAD

**Issue by chnuessli** [sosm/osmhistorydb-ch#12]
Maybe i have egg's on the eyes, but i can't see some posibility to set a data range on the graphics.
@samadelli maybe you can help me out?

**Comment by sfkeller** [comment]
Look at chart "Changed defibrillators: **Filter**" lower right:
![grafik](https://user-images.githubusercontent.com/43340/128358562-1bf44e88-ab6a-48e7-8ec4-be5ab5bfca38.png)

**Comment by sfkeller** [comment]
Seems that e.g. choosing "Custom > **last 5 days**" (given we have the 5th of August today) - followed by "Apply" - is the quickest way to set the time range.
