### ISSUE TITLE
Warum werden mit Filter keine Daten älter März 2021 angezeigt (und weitere Fragen)?

### ISSUE THREAD

**Issue by sfkeller** [sosm/osmhistorydb-ch#8]
Beim Dashboard https://potm.osm.ch/superset/dashboard/11/ habe ich im Filter noch nebst User/Mapper noch "Time" dazukonfiguriert. Komischerweise werden keine Daten älter als März 2021 angezeigt! Da stimmt etwas hinter unserem PotM nicht. 

@datendelphin meint: "Es kann auch ein Fehler beim importieren sein. Such mal gezielt nach alten versionen. Z.B. alle versionen von einem node den es schon lange gibt."

**Comment by samadelli** [comment]
Im Dataset, auf dem die Charts des Dashboards basieren, wird nach dem letzten Monat gefiltert. Ich habe das jetzt rausgenommen. Jetzt sollten alle Daten angezeigt werden.

**Comment by sfkeller** [comment]
1. Kannst du den Default "1 week" noch auf "1 month" zu ändern versuchen?
1. Dann nochmals Christian Nüssli fragen, ob das Dashboard nun so OK sei ?
1. Das definitie "PotM Defi" mit Christian besprechen und auf Mai 2021 erzeugen (separates Dashboard)
1. Und überlegen, wie das definitive "PotM Defi" auf französisch realisiert werden kann wo möglichst alle Queries weitergenutzt werden können
1. Alle diese Angaben so dokumentieren (und im GIT ablegen!), dass das übernächste PotM einfacher geplant werden kann.
