### ISSUE TITLE
implausibly high numbers of changes reported on potm.osm.ch

### ISSUE THREAD

**Issue by tyrasd** [sosm/osmhistorydb-ch#9]
The following screenshot shows a high number of modified "schools" for a particular user:

[<img src="https://user-images.githubusercontent.com/1927298/121213061-34ab2d00-c87e-11eb-9f44-3eb981a660a9.png" width="40%"/>](https://user-images.githubusercontent.com/1927298/121213061-34ab2d00-c87e-11eb-9f44-3eb981a660a9.png)

As this number seemed to be _very_ high at first glance, I tried to confirm/investigate it using other tools, including the [OSHDB](https://github.com/giscience/oshdb). I eventually found only a much lower number of edits of matching features by this user: around 40. Also a looking at all edits by the user e.g. on [osmcha](https://osmcha.org/?filters=%7B%22users%22%3A%5B%7B%22label%22%3A%22Lirum%20Larum%22%2C%22value%22%3A%22Lirum%20Larum%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22label%22%3A%222021-05-01%22%2C%22value%22%3A%222021-05-01%22%7D%5D%2C%22date__lte%22%3A%5B%7B%22label%22%3A%222021-06-01%22%2C%22value%22%3A%222021-06-01%22%7D%5D%7D) does not match the high number reported on potm.osm.ch.

The issue is also present on the defibrillator dashboard and gets even more pronounced when selecting the full time rage:

[<img src="https://user-images.githubusercontent.com/1927298/121217079-ca948700-c881-11eb-94e3-9332862166c8.png" width="40%"/>](https://user-images.githubusercontent.com/1927298/121217079-ca948700-c881-11eb-94e3-9332862166c8.png)

Since in Switzerland there are currently only about [5000 defibrillators mapped in OSM](http://taginfo.geofabrik.de/europe/switzerland/tags/emergency=defibrillator), the reported numbers would mean that the top user would have had to edit each defibrillator hundreds of times. :see_no_evil: In my calculations, I found that this top user actually "only" contributed a total number of ~8,200 modifications to defibrillators in OSM (again only 1% of the number reported by PotM).

**Comment by sfkeller** [comment]
Yes. There must be an error in the counting. 
From my "feeling" this has to do with the SQL and the history db.

**Comment by tyrasd** [comment]
The numbers look much more reasonable now. :blush: :+1:
